logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: conference-crud-app

  datasource:
    url: jdbc:h2:mem:mydb
    platform: h2
    initialization-mode: always
  h2:
    console:
      enabled: true



# https://stackoverflow.com/questions/67744719/spring-boot-data-jpa-with-h2-and-data-sql-table-not-found
  jpa:
    defer-datasource-initialization: true
#  jpa:
#    generate-ddl: true
#
#
#
#    hibernate:
#      ddl-auto: update



server:
  port: 8081